# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "D:\\codingzone\\devops\\vagrant\\devwork", "/vagrantws"   
end
